@host = http://localhost:3000
@contentType = application/json
@bearer_token = Bearer {{auth_login.response.body.$.token}}

# @name auth_login
POST {{host}}/auth/login HTTP/1.1
Content-Type: {{contentType}}

{
  "username": "user",
  "password": "user"
}

###
# @name auth_me
GET {{host}}/auth/me HTTP/1.1
Authorization: {{bearer_token}}

###
# @name order_create
POST {{host}}/order HTTP/1.1
Host: localhost:3000
Content-Type: {{contentType}}
Authorization: {{bearer_token}}

{
  "items": [
    {
      "product_id": "04c4353a-3f6d-4272-a8f2-44b82c05ecc0",
      "quantity": 2
    }
      ],
  "card_hash": "321321"
}

###
# @name order_find_all
GET {{host}}/order
Authorization: {{bearer_token}}

###
# @name order_find_by_id
@order_id = {{order_find_all.response.body.$[0].id}}
GET {{host}}/order/{{order_id}}
Authorization: {{bearer_token}}


###
# @name product_create
# @prompt productName
POST {{host}}/product HTTP/1.1
  Host: localhost:3000
Content-Type: {{contentType}}

{
  "name": "Product {{productName}}",
  "image_url": "https://via.placeholder.com/150",
  "description": "{{productName}} description",
  "price": 12313
}

###
# @name product_find_many
@product_id = {{product_find_many.response.body.$[0].id}}
GET {{host}}/product

###
# @name product_find_by_id
GET {{host}}/product/{{product_id}}