version: "3"

services:
  catalog_api:
    image: mysql:latest
    container_name: catalog_mysql_db
    profiles: [apis]
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=catalog_db
    volumes:
      - .docker/api_catalog:/var/lib/mysql
      - ./apps/api-catalog/db.sql:/docker-entrypoint-initdb.d/db.sql
    restart: always

  order_api:
    image: mysql:latest
    container_name: order_mysql_db
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=product_db_dev
      - MYSQL_PASSWORD=root
    volumes:
      - .docker/mysql:/var/lib/mysql
    restart: always

  order_queue:
    image: rabbitmq:3.12-management
    profiles: [apis]
    container_name: rabbitmq
    hostname: rabbit
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - .docker/rabbitmq:/var/lib/rabbitmq