// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package rabbitmqservice

import (
	"github.com/wscnd/nx-imfs-17/payment/pkg/rabbitmqinit"
)

// Injectors from wire.go:

func Init() (*RabbitMqService, func()) {
	channel, cleanup := rabbitmqinit.Init()
	rabbitMqService := Must(channel)
	return rabbitMqService, func() {
		cleanup()
	}
}
